### ISSUE TITLE
Increaing font size to some huge value make cursor disappear

### ISSUE THREAD

**Issue by kchibisov** [w23/alacritty#25]
If you increase font size with `ctrl +` to some big value, the cursor will completely disappear and there won't be a way to get it back with decreasing the font size again.

**Comment by w23** [comment]
I've looked into this and turns out this is a hard problem! What triggers it is the fact that for large font sizes atlas textures get too small to fit even basic ASCII plane, and many glyphs *including cursor* spill into second atlas. Current rendering model depend on all background-like things to be rendered in the first (main) grid pass.

There are three parts:
1. (have a fix) cursor support was completely pass-unaware, so random glyphs were rendered instead of it when this is triggered
2. (have a fix) When the cursor glyph is not in the first atlas, it will not be rendered at all as only main pass does cursor blending
3. (no idea how to fix locally) When the cursor is not in the main pass, but the glyph under cursor is, cursor will overwrite the glyph, as it is rendered after.

I can try to add all possible cursors glyphs into the very beginning of the grid atlas as a workaround.

**Comment by kchibisov** [comment]
I the problem is cursor being in a wrong atlas, you may put it in a propor atlas on reload, since on font reload you should drop all existing atlases anyway?
